export class DashboardView {
    constructor(container, app) {
        this.container = container;
        this.app = app;
        this.cases = this.app.storage.loadCases();
    }

    calculateStats() {
        const now = new Date();
        const next7Days = new Date(); next7Days.setDate(now.getDate() + 7);
        const next30Days = new Date(); next30Days.setDate(now.getDate() + 30);

        let stats = {
            totalCases: this.cases.length,
            activeCases: 0,
            suspendedCases: 0,
            currentWeek: 0,
            currentMonth: 0,
            criticalJudgments: 0,
            tasks: []
        };

        this.cases.forEach(c => {
            if (c.operationalStatus === 'suspended_administrative') stats.suspendedCases++;
            if (c.operationalStatus === 'new' || c.operationalStatus === 'active' || c.operationalStatus === 'متداول') stats.activeCases++;

            // Check if "Current" and has sessions in range
            if (c.operationalStatus === 'متداول') {
                const sessions = c.sessions || [];
                // Add lastSessionDate if it's future
                const allDates = [...sessions.map(s => s.date), c.lastSessionDate].filter(Boolean);
                
                const hasSessionIn = (days) => {
                    const limit = new Date(); limit.setDate(now.getDate() + days);
                    return allDates.some(dStr => {
                        const d = new Date(dStr);
                        return !isNaN(d) && d >= now && d <= limit;
                    });
                };

                if (hasSessionIn(7)) stats.currentWeek++;
                if (hasSessionIn(30)) stats.currentMonth++;
            }

            // Check judgments requiring review (ضد أو يحتاج مراجعة)
            if (c.judgments) {
                stats.criticalJudgments += c.judgments.filter(j => j.classification === 'ضد' || j.classification === 'مراجعة').length;
            }

            // Collect tasks/reminders generated by Rules Engine
            if (c.reminders) {
                c.reminders.forEach(r => {
                    stats.tasks.push({
                        type: 'reminder',
                        title: r.title,
                        caseNumber: c.caseNumber,
                        court: c.court,
                        caseId: c.id
                    });
                });
            }
            if (c.tasks) {
                c.tasks.forEach(t => {
                    if (t.status !== 'completed') {
                        stats.tasks.push({
                            type: 'task',
                            title: t.title,
                            priority: t.priority,
                            caseNumber: c.caseNumber,
                            court: c.court,
                            caseId: c.id
                        });
                    }
                });
            }
        });

        return stats;
    }

    render() {
        const stats = this.calculateStats();
        
        let tasksHtml = '';
        if (stats.tasks.length === 0) {
            tasksHtml = '<p class="empty-msg">لا توجد حركات مؤخراً. ابدأ بإضافة قضية جديدة.</p>';
        } else {
            tasksHtml = '<ul class="task-list-items">';
            stats.tasks.forEach(t => {
                const icon = t.type === 'reminder' ? 'alarm-outline' : 'checkmark-circle-outline';
                const colorClass = t.priority === 'high' ? 'text-danger' : 'text-primary';
                tasksHtml += `
                    <li class="task-item" data-case-id="${t.caseId}">
                        <div class="task-icon ${colorClass}"><ion-icon name="${icon}"></ion-icon></div>
                        <div class="task-content">
                            <h4>${t.title}</h4>
                            <span class="task-meta">ملف الطعن: ${t.caseNumber} - ${t.court}</span>
                        </div>
                        <button class="btn-icon view-task-case"><ion-icon name="arrow-back-outline"></ion-icon></button>
                    </li>
                `;
            });
            tasksHtml += '</ul>';
        }

        this.container.innerHTML = `
            <div class="page-header">
                <div class="header-titles">
                    <h2>نظرة عامة (اللوحة التشغيلية)</h2>
                    <p>ملخص لحالة العمليات الإجرائية والمهام المستحقة بناءً على القواعد الذكية</p>
                </div>
            </div>

            <div class="dashboard-grid">
                <div class="stat-card">
                    <h3>إجمالي القضايا النشطة</h3>
                    <div class="value">${stats.activeCases}</div>
                </div>
                <div class="stat-card">
                    <h3>متداول هذا الأسبوع</h3>
                    <div class="value">${stats.currentWeek}</div>
                </div>
                <div class="stat-card">
                    <h3>متداول هذا الشهر</h3>
                    <div class="value">${stats.currentMonth}</div>
                </div>
                <div class="stat-card warning">
                    <h3>أحكام حرجة (ضد)</h3>
                    <div class="value">${stats.criticalJudgments}</div>
                </div>
            </div>
            
            <section class="recent-section">
                <h2>الإجراءات والمهام المطلوبة (Rules Engine)</h2>
                <div class="task-list">
                    ${tasksHtml}
                </div>
            </section>
        `;

        this.setupEvents();
    }

    setupEvents() {
        this.container.querySelectorAll('.task-item').forEach(item => {
            item.addEventListener('click', () => {
                document.dispatchEvent(new CustomEvent('navigate', { 
                    detail: { page: 'case-details', id: item.dataset.caseId } 
                }));
            });
        });
    }
}
